server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

auth:
  expiration: 604800
  secret: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCY4m6CdD231KvT
    wpUB8B8PhajLrI9Ma7IRR6m5wp+PWPsxAkBhLmZA2P1PoZzyEgkmt2jlBfDwXYoq
    0bmHp4YmgwokGMwshkIDnVnJIyV4eOBXUPYZGO32mo5hFzthcjpYo0jZqJihEFbv
    +ShKevQN9pTHUQd9BtWfRjofIY2qhQWlvVWK5aCnsUEm3YsIoY2HohzMjSuFbMoB
    9VWocxdJKwkGfjO4/9kjAUs/Ty3jpDTbZSu1VBzeh1c1xr0PVAT77vXEjyEmRM4Z
    E/R7+ZdJ31UzZUQbpkIb/LkJ9YfD9V2tMlHR4ppCn4OZIoB2twwESeUzNzQJO8nn
    x7/nUoTLAgMBAAECggEAbiI377wjNcl7monC4+mBxqHHjimZ9Thjx3TzfIEKhq5Y
    Dd8MV7WgLbjjCjlnIS8C7qQTaWCVR+JqhRwd5e41gorFhGlks/Jnncj9hBrQhG+3
    VM9a6Yt+6TY/uQuOWE18YJwH/9wnT2fA6RB5COZ355MpbEgf994zh5CEkCaQsjQM
    wT1hxblgc+9iaRUqfvgWXh3oHNLvZ9NukU+v0noAhvj4dutdZ4UG6dFp29NvKcat
    TyeQ3PTYYFN7SMRnhg9NlWUbLKJLNZ4LZrHsIpFcVKIQWdVg5wI0H6AF+7sS0/Wi
    2PuO2C9wc21Vklt9usGJ8iq115hRnh1CRSNTzP0HaQKBgQDxaeBrLdfjbiw5kogd
    YKKKhdR6UgM+vnCVqW+tv9fzm8BBbAaVARlQAtdHiRcVnHzDTV5NBHbettEybLM4
    bGBeIBJixcKWWqMYNPAJVy/9CnZSb9prDOPXbYQJZuoCAMzz+JSptf+C0/PK7Von
    wbk3QcuaVCsXwkCtKyNx6EhhjwKBgQCiHzW8QtiZGTltf19smoHeyg8Pl0nV5rUd
    I5ePZe+4DW4UYXNyx99uC/Pr9yxZjtAU70CXiNIm7KJvZbCHiPffVd/KxEshZkND
    DNm1JOYQyy1x8lWUOmupeBxEiKBfHyXAZCDEdBvqX1Ip+D0wdy3sr2ykbVOVM4lf
    vBXiSyUTBQKBgBqz3FfelT+ZwxiHJbkiJDhwPyVchvFcvTVArZKpYqiWdLiHy16V
    5YfdGJTYDA6e5Ynwt9qLAN73l8IdFeHK0wn2QDJer3xUADBAQsC1vSAfFSFfL+ih
    X15HxdAIax/XmNPvjfoLoHyHFzM997foDKWZCH1EjBOvr9m3qM8Do2XvAoGAb3Mf
    IK2fcxgZF4IxmlpZH0wusFwjoQ15wm9eWHEOK6vn2dDoaaannWJQLA3+ig6YU1vq
    PoILXkDcpdH1Wic5p2nEcAMjVvGTGbvyygl0s2TJeATM+hpzOsxcOmzmOp4R+MGc
    mRDsw+EFfd6uSewUQRqTiDGz/OSx8oM9VBSuhvUCgYEAp/MHD6U2lW6Kjbh9wE2R
    c6pfPryFKgOz8VUvXEdPmuLj/OyMS9iOL7JXyPZGBKKPWPfELRruFGdMXb3Cq0kq
    atcao82eHDMBEAHOYMUGf5BUIm5MYV4hz7wxaFwWWj9RfDLz/C95frAfs0SRWzbc
    DJmj7ayL3KoQ4fKDLICZxd0=
  header: Authorization